name: Generate docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Nim ${{ matrix.nim-version }}
      uses: jiro4989/setup-nim-action@master
      with:
        nim-version: "stable"
    - name: Generate docs
      run: nim doc src/httpquery.nim
    - name: Deploy docs
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        git branch gh-pages
        git checkout gh-pages
        
        mv src/htmldocs docs
        
        git add docs
        git commit -m 'Generate docs'
        
        git push -f origin gh-pages
        